server.port=${PORT:8080}
server.servlet.context-path=${BASE_ROUTE}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=${MONGODB_CREATION}

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

spring.jackson.serialization.write-dates-as-timestamps=${TIMESTAMPS}
spring.jackson.time-zone=${TIME_ZONE}

logging.level.org.springframework=${SPRING_LOGGING_LEVEL:INFO}
logging.level.com.tarcom=${APP_LOGGING_LEVEL:DEBUG}
