server.port=${PORT:8080}
server.servlet.context-path=${BASE_ROUTE:/api}

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/tarcom}
spring.data.mongodb.auto-index-creation=${MONGODB_CREATION:true}

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:100MB}

spring.jackson.serialization.write-dates-as-timestamps=${TIMESTAMPS:false}
spring.jackson.time-zone=${TIME_ZONE:UTC}

logging.level.org.springframework=${SPRING_LOGGING_LEVEL:INFO}
logging.level.com.tarcom=${APP_LOGGING_LEVEL:DEBUG}

